### ISSUE TITLE
Habit Loop Schema

### ISSUE THREAD

**Issue by dojr** [osu-cascades/habit-loop-server#1]
Need to flesh out the schema for a habit so we can continue developing the back-end and create a dynamodb table.

My thoughts so far:

User:
- **username/email**: a string with the associated users id
- **password**: not plaintext of course
- **streak**: amount days that the user has consistently and continuously trained for 30 minutes 
- **habit**: current habit the user is shown to be working on
- **habits**: list of habits that the user has created or has been assigned to
- **isManager**: boolean value to specify if the user is a manager (still thinking on if this is necessary)

Habit:
- **unique_id**: a string of a uuid
- **title**: a string for the name of the habit
- **type**: array of technologies involved (ex. ["front-end", "react", "state management"])
- **created_at**: a date string 
- **updated_at**: when the habit was last updated
- **time_spent**: total time spent training this habit
- **priority**: The priority indicates the most important habits to do. A manager can assign priorities to habits in order to get employees to train on those before other habits.

Will continue to add to this list as time goes on. And feel free to recommend changes or additions.

Priorities could be designed like this:
- High priority = 1
- Medium Priority = 2
- Low Priority = 3

Where high priority can only be assigned to 1 habit, medium can be assigned to 2 or 3 and low for the rest.

**Comment by phelanjo** [comment]
@dojr is this safe to close?
